name: properties
version: 0.5.4
author: Lorenzo Cavina <cavina.lorenzo@gmail.com>
description: A simple library to manage properties file (and something more) in Dart
homepage: http://code.google.com/p/dart-properties/
documentation: http://code.google.com/p/dart-properties/source/browse/tags/0.5.2/#0.5.2%2Fdoc
environment:
  sdk: 0.5.13+1.r23552
dependencies:
  meta: 0.5.13
  unittest: 0.5.13

#0.5.2%2Fdoc
#0.5.2%2Fdoc
#0.5.2%2Fdoc
#0.5.2%2Fdoc
#0.5.2%2Fdoc
#0.5.1%2Fdoc
#0.5.1%2Fdoc
#0.5.0%2Fdoc
#0.5.0%2Fdoc