name: properties
version: 0.4.4
author: Lorenzo Cavina <cavina.lorenzo@gmail.com>
description: A simple library to manage properties file (and something more) in Dart
homepage: http://code.google.com/p/dart-properties/
dependencies:
  unittest: any
